name: Collation

on:
  workflow_dispatch:


env:
  BRANCH_PREFIX: updated-codes

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Try to checkout exising PR branch
        id: compare
        run: |
          # Check Genesis and SpecVersion
          RenewedGenesis=$(curl -X POST http://rpc.vara-network.io/jsonrpc -H 'Content-Type: application/json' -d '[ { "id": 1, "jsonrpc": "2.0", "method": "chain_getBlockHash", "params": [0]}]'  | jq -r '.[].result');
          RenewedSpecVersion=$(curl -X POST http://rpc.vara-network.io/jsonrpc  -H 'Content-Type: application/json' -d '[ { "id": 1, "jsonrpc": "2.0", "method": "state_getRuntimeVersion", "params": []}]'  | jq -r '.[].result.specVersion'); 
          # Read previous Genesis and SpecVersion from file
          originalgenesis=$(sed '1!d' spec.info)
          originalspecVersion=$(sed '2!d' spec.info)
          NewValue="$RenewedGenesis\n$RenewedSpecVersion"
          # Compare
          if [ "$originalspecVersion" -ne "$RenewedSpecVersion" ] || [ "$originalgenesis" != "$RenewedGenesis" ]
          then echo "Sper or Genesis change" && echo -e "$NewValue"  > spec.info && echo "::set-output name=metaChanged::true"
          else echo "Spec and Genesis haven't changed"
          fi
          
      - name: Echo
        if: ${{ steps.compare.outputs.metaChanged == 'true' }}
        run: echo 'Meta Changed'
